-- Enable foreign key constraints in H2
SET REFERENTIAL_INTEGRITY TRUE;

-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    date_of_birth DATE,
    role VARCHAR(10) NOT NULL,
    profile_picture VARCHAR(500),
    gender VARCHAR(10),
    address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(50),
    zip_code VARCHAR(20),
    country VARCHAR(100),
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verification_token VARCHAR(255),
    reset_password_token VARCHAR(255),
    reset_password_expires TIMESTAMP,
    last_login TIMESTAMP,
    login_attempts INT NOT NULL DEFAULT 0,
    locked_until TIMESTAMP,
    license_number VARCHAR(50),
    specialization VARCHAR(100),
    experience_years INT,
    consultation_fee DECIMAL(10,2),
    nurse_license VARCHAR(50),
    certification VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (email),  -- Ensure unique constraint on email
    UNIQUE (phone_number)  -- Optional: Ensure phone number is unique if needed
);
-- Create departments table
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500),
    location VARCHAR(100),
    floor_number INT,
    building VARCHAR(100),
    contact_number VARCHAR(20),
    email VARCHAR(255),
    head_of_department_id BIGINT,
    is_emergency_department BOOLEAN NOT NULL DEFAULT FALSE,
    is_surgical BOOLEAN NOT NULL DEFAULT FALSE,
    operating_hours_start VARCHAR(8),
    operating_hours_end VARCHAR(8),
    working_days VARCHAR(50),
    total_beds INT,
    available_beds INT,
    icu_beds INT,
    emergency_beds INT,
    specialties VARCHAR(1000),
    services VARCHAR(2000),
    equipment VARCHAR(2000),
    doctors_count INT NOT NULL DEFAULT 0,
    nurses_count INT NOT NULL DEFAULT 0,
    is_active_department BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (head_of_department_id) REFERENCES users(id) ON DELETE SET NULL
);
-- Create patients table
CREATE TABLE IF NOT EXISTS patients (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    primary_doctor_id BIGINT,
    department_id BIGINT,
    patient_id VARCHAR(20) NOT NULL UNIQUE,
    blood_group VARCHAR(5),
    height_cm DECIMAL(5,2),
    weight_kg DECIMAL(5,2),
    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(20),
    emergency_contact_relationship VARCHAR(50),
    insurance_provider VARCHAR(200),
    insurance_policy_number VARCHAR(50),
    insurance_group_number VARCHAR(50),
    insurance_photo VARCHAR(500),
    primary_language VARCHAR(50),
    occupational_history VARCHAR(1000),
    marital_status VARCHAR(20),
    educational_background VARCHAR(500),
    religion VARCHAR(50),
    nutrition_status VARCHAR(20),
    tobacco_use BOOLEAN NOT NULL DEFAULT FALSE,
    alcohol_use BOOLEAN NOT NULL DEFAULT FALSE,
    exercise_habits VARCHAR(1000),
    travel_history VARCHAR(1000),
    current_medications VARCHAR(2000),
    known_allergies VARCHAR(1000),
    previous_surgeries VARCHAR(2000),
    family_medical_history VARCHAR(2000),
    admission_date DATE,
    discharge_date DATE,
    admission_type VARCHAR(20),
    discharge_status VARCHAR(20),
    current_room_number VARCHAR(20),
    bed_number VARCHAR(10),
    admission_notes VARCHAR(2000),
    discharge_instructions VARCHAR(2000),
    follow_up_required BOOLEAN NOT NULL DEFAULT FALSE,
    follow_up_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (primary_doctor_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);
-- Create appointments table
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    nurse_id BIGINT,
    appointment_date DATE NOT NULL,
    appointment_time TIME NOT NULL,
    duration_minutes INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    notes VARCHAR(1000),
    symptoms VARCHAR(1000),
    diagnosis VARCHAR(1000),
    treatment_plan VARCHAR(2000),
    follow_up_date DATE,
    cancellation_reason VARCHAR(500),
    cancellation_date TIMESTAMP,
    actual_visit_time TIMESTAMP,
    visit_duration_minutes INT,
    prescription_count INT,
    is_emergency BOOLEAN NOT NULL DEFAULT FALSE,
    consultation_fee DECIMAL(10,2),
    paid_amount DECIMAL(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (nurse_id) REFERENCES users(id) ON DELETE SET NULL
);
-- Create medical_records table
CREATE TABLE IF NOT EXISTS medical_records (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    appointment_id BIGINT,
    record_date DATE NOT NULL,
    record_type VARCHAR(20) NOT NULL,
    chief_complaint VARCHAR(500) NOT NULL,
    present_illness VARCHAR(2000),
    medical_history VARCHAR(2000),
    family_history VARCHAR(2000),
    social_history VARCHAR(1000),
    allergies VARCHAR(1000),
    medications VARCHAR(2000),
    physical_examination VARCHAR(2000),
    vital_signs VARCHAR(1000),
    weight DECIMAL(5,2),
    height DECIMAL(5,2),
    blood_pressure_systolic INT,
    blood_pressure_diastolic INT,
    heart_rate INT,
    temperature DECIMAL(4,1),
    respiratory_rate INT,
    oxygen_saturation DECIMAL(4,1),
    laboratory_tests VARCHAR(2000),
    imaging_studies VARCHAR(2000),
    procedures VARCHAR(2000),
    assessment VARCHAR(2000) NOT NULL,
    plan VARCHAR(2000) NOT NULL,
    follow_up_instructions VARCHAR(1000),
    next_appointment_date DATE,
    progress_notes VARCHAR(2000),
    is_confidential BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE SET NULL
);
